[package]
name = "touch_test"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
embedded-graphics.workspace = true
embedded-hal.workspace = true
esp-backtrace.workspace = true
esp-bootloader-esp-idf.workspace = true
esp-hal.workspace = true
esp-println.workspace = true
heapless.workspace = true
nesso-n1 = { path = "../../crates/nesso-n1" }
nesso-touch = { path = "../../crates/nesso-touch" }

[lints]
workspace = true

[[bin]]
name = "touch_test"
path = "src/main.rs"
test = false
bench = false
