[package]
name = "nesso-wifi"
description = "ESP32-C6 Wi-Fi support for Arduino Nesso N1 using esp-radio."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
embassy-futures.workspace = true
esp-hal.workspace = true
esp-radio.workspace = true
esp-rtos.workspace = true
heapless.workspace = true

[lints]
workspace = true

[lib]
test = false
bench = false
