[package]
name = "audio_test"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
esp-backtrace.workspace = true
esp-bootloader-esp-idf.workspace = true
esp-hal.workspace = true
esp-println.workspace = true
nesso-audio = { path = "../../crates/nesso-audio" }
nesso-n1 = { path = "../../crates/nesso-n1" }

[lints]
workspace = true

[[bin]]
name = "audio_test"
path = "src/main.rs"
test = false
bench = false
