[package]
name = "nesso-input"
description = "Button event state machines for Arduino Nesso N1 applications."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[lib]
test = false
bench = false
