[package]
name = "nesso"
description = "Rust SDK facade for Arduino Nesso N1 on ESP32-C6."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
nesso-audio = { path = "../nesso-audio", version = "0.0.1" }
nesso-display = { path = "../nesso-display", version = "0.0.1" }
nesso-imu = { path = "../nesso-imu", version = "0.0.1" }
nesso-input = { path = "../nesso-input", version = "0.0.1" }
nesso-n1 = { path = "../nesso-n1", version = "0.0.1" }
nesso-power = { path = "../nesso-power", version = "0.0.1" }
nesso-storage = { path = "../nesso-storage", version = "0.0.1" }
nesso-touch = { path = "../nesso-touch", version = "0.0.1" }
nesso-wifi = { path = "../nesso-wifi", version = "0.0.1" }

[lints]
workspace = true

[lib]
test = false
bench = false
