[package]
name = "nesso"
description = "Rust SDK facade for Arduino Nesso N1 on ESP32-C6."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version = "0.0.6"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
bmi2.workspace = true
embedded-graphics.workspace = true
embedded-hal.workspace = true
embassy-futures = { workspace = true, optional = true }
esp-hal.workspace = true
esp-radio = { workspace = true, optional = true }
esp-rtos = { workspace = true, optional = true }
esp-storage = { version = "0.9.0", default-features = false, features = [
    "esp32c6",
] }
embedded-storage = "0.3.1"
heapless.workspace = true
libm = { version = "0.2.15", default-features = false }

[features]
default = []
ble = ["dep:esp-radio", "dep:esp-rtos", "esp-radio/ble"]
env = []
wifi = [
    "dep:embassy-futures",
    "dep:esp-radio",
    "dep:esp-rtos",
    "esp-radio/wifi",
]

[package.metadata.docs.rs]
default-target = "riscv32imac-unknown-none-elf"
targets = ["riscv32imac-unknown-none-elf"]
cargo-args = ["-Z", "build-std=core,alloc"]

[lints]
workspace = true

[lib]
test = false
bench = false
