[package]
name = "nesso-imu"
description = "BMI270 IMU support for Arduino Nesso N1."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
bmi2.workspace = true
embedded-hal.workspace = true
libm = { version = "0.2.15", default-features = false }

[lints]
workspace = true

[lib]
test = false
bench = false
