[package]
name = "input_test"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version = "0.0.0"

[dependencies]
nesso = { path = "../../crates/nesso" }
embedded-graphics.workspace = true
embedded-hal.workspace = true
esp-backtrace.workspace = true
esp-bootloader-esp-idf.workspace = true
esp-hal.workspace = true
esp-println.workspace = true
heapless.workspace = true

[lints]
workspace = true

[[bin]]
name = "input_test"
path = "src/main.rs"
test = false
bench = false
